# Generated by Django 5.0.3 on 2024-03-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStudent', models.CharField(max_length=50, verbose_name='ФИО')),
                ('groupStudent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.groupmodel', verbose_name='Группа')),
            ],
        ),
    ]
