# Generated by Django 5.0.3 on 2024-03-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': 'Студента', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='curatorStudent',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.curatormodel', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='groupStudent',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.groupmodel', verbose_name='Группа'),
        ),
    ]
