# Generated by Django 5.0.3 on 2024-03-22 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_citizenshipmodel'),
        ('student', '0002_alter_studentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='citizenshopStudent',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.citizenshipmodel', verbose_name='Гражданство'),
        ),
    ]
