# Generated by Django 5.0.3 on 2024-03-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentmodel_citizenshopstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='citizenshopStudent',
            new_name='citizenshipStudent',
        ),
    ]
