# Generated by Django 5.0.3 on 2024-03-22 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_citizenshopstudent_studentmodel_citizenshipstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='dateOfBdStudent',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
