# Generated by Django 5.0.3 on 2024-03-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentmodel_dateofbdstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='childrensInfoStudent',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о детях в семье'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='faterInfoStudent',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об отце'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='motherInfoStudent',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о матери'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='placeOfResidenceStudent',
            field=models.TextField(null=True, verbose_name='Место проживания'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='placeOfregistrationStudent',
            field=models.TextField(null=True, verbose_name='Место прописки'),
        ),
    ]
