# Generated by Django 5.0.6 on 2024-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentmodel_childrensinfostudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='education',
            field=models.CharField(max_length=100, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='identificationNumber',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер удостоверения'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='iin',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='languageOfStudy',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('kz', 'Казахский')], max_length=2, null=True, verbose_name='Язык обучения'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='student_photos/', verbose_name='Фото'),
        ),
    ]
