# Generated by Django 5.0.6 on 2024-05-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_usermodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
