# Generated by Django 5.0.6 on 2024-05-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_delete_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='education',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='identificationNumber',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='iin',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='languageOfStudy',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='photo',
        ),
    ]
