# Generated by Django 5.0.6 on 2024-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentmodel_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='iin',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИИН'),
        ),
    ]
