# Generated by Django 5.0.6 on 2024-05-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_studentmodel_iin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='iin',
        ),
    ]
