# Generated by Django 5.0.6 on 2024-05-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_studentmodel_iin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='education',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='identificationNumber',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='languageOfStudy',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='photo',
        ),
    ]
